#pragma once

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @file gbk_utf8.h
 * @brief GBK → UTF-8 transcoding for barcode scanner input.
 *
 * The CX70/FM430 scanner emits GBK-encoded bytes over CDC-ACM. LVGL and the
 * cloud JSON layer both require UTF-8, so dispatch_barcode() runs every scan
 * through gbk_to_utf8() before forwarding it downstream.
 *
 * The lookup table (gbk_to_unicode, 21791 entries, ~47 KiB in flash) is
 * generated by tools/gen_gbk_table.py from Python's 'gbk' codec.
 */

/** Dense GBK→Unicode table. Indexed by [lead-0x81][trail_index(trail)].
 *  Defined in gbk_table.c (generated). 0 = undefined codepoint. */
extern const uint16_t gbk_to_unicode[126][190];

/**
 * Convert a GBK byte buffer to a NUL-terminated UTF-8 string.
 *
 * ASCII bytes (0x00-0x7F) pass through unchanged. GBK double-byte sequences
 * are looked up in gbk_to_unicode and re-encoded as UTF-8 (2-3 bytes).
 * Undefined/invalid sequences become U+FFFD (REPLACEMENT CHARACTER).
 *
 * Output is truncated at a UTF-8 character boundary if it would overflow
 * utf8_cap — downstream never sees a partial multi-byte sequence.
 *
 * @param gbk       Input bytes (GBK-encoded, may contain ASCII inline).
 * @param gbk_len   Number of valid bytes in gbk (not counting any NUL).
 * @param utf8      Output buffer; receives the UTF-8 string + NUL.
 * @param utf8_cap  Total capacity of utf8 (including NUL byte space).
 * @return Number of UTF-8 bytes written, EXCLUDING the NUL terminator.
 *         Returns 0 if the input is empty or all inputs are NULL/zero-cap.
 */
size_t gbk_to_utf8(const uint8_t *gbk, size_t gbk_len,
                   char *utf8, size_t utf8_cap);

#ifdef __cplusplus
}
#endif
